[workspace]
resolver = "2"
members = [
    "./pin-contract",
    "./pin-token",
    "./pin-treasury",
]

[workspace.dependencies]
fuels = "0.50"
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }
