[project]
authors = ["PopcornPaws"]
entry = "main.sw"
license = "Apache-2.0"
name = "guild-pin-contract"

[dependencies]
#ownership = { git = "https://github.com/FuelLabs/sway-libs", rev = "a585660" }
#src_20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.0" }
#src_5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.0" }
# cannot compile these because the updated compiler throws an error
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.22.0" }
