[package]
name = "guild-pin-token-contract"
version = "0.0.0"
authors = ["PopcornPaws"]
edition = "2021"

[dev-dependencies]
fuels = "0.50"
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
