[project]
authors = ["PopcornPaws"]
entry = "main.sw"
license = "Apache-2.0"
name = "guild-pin-token-contract"

[dependencies]
guild-pin-common = { path = "../pin-common" }
guild-pin-treasury-contract = { path = "../pin-treasury" }
ownership = { git = "https://github.com/FuelLabs/sway-libs", rev = "a585660" }
src_20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.0" }
src_3 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.0" }
src_5 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.2.0" }
